//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidForensics.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AndroidForensics.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /data/data/com.google.android.browser/databases.
        /// </summary>
        public static string AndroidBrowser {
            get {
                return ResourceManager.GetString("AndroidBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autofill.db.
        /// </summary>
        public static string AndroidBrowser_AutoFill {
            get {
                return ResourceManager.GetString("AndroidBrowser_AutoFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browser2.db.
        /// </summary>
        public static string AndroidBrowser_Browser2 {
            get {
                return ResourceManager.GetString("AndroidBrowser_Browser2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to webview.db.
        /// </summary>
        public static string AndroidBrowser_WebView {
            get {
                return ResourceManager.GetString("AndroidBrowser_WebView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Connected {
            get {
                object obj = ResourceManager.GetObject("Connected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Disconnected {
            get {
                object obj = ResourceManager.GetObject("Disconnected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /data/data/com.google.android.gsf/databases.
        /// </summary>
        public static string ProvidersTelephony {
            get {
                return ResourceManager.GetString("ProvidersTelephony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mmssms.db.
        /// </summary>
        public static string ProvidersTelephony_MMSSMS {
            get {
                return ResourceManager.GetString("ProvidersTelephony_MMSSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to talk.db.
        /// </summary>
        public static string ProvidersTelephony_Telephony {
            get {
                return ResourceManager.GetString("ProvidersTelephony_Telephony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
